USE DATABASE SANDBOX;
USE SCHEMA STAGE_SCH;

CREATE OR REPLACE TABLE STAGE_SCH.LOCATION (
    LOCATIONID TEXT,
    CITY TEXT,
    STATE TEXT,
    ZIPCODE TEXT,
    ACTIVEFLAG TEXT,
    CREATEDDATE TEXT,
    MODIFIEDDATE TEXT,
    _STG_FILE_NAME TEXT,
    _STG_FILE_LOAD_TS TIMESTAMP,
    _STG_FILE_MD5 TEXT,
    _COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COPY INTO STAGE_SCH.LOCATION (
    LOCATIONID,
    CITY,
    STATE,
    ZIPCODE,
    ACTIVEFLAG,
    CREATEDDATE,
    MODIFIEDDATE,
    _STG_FILE_NAME,
    _STG_FILE_LOAD_TS,
    _STG_FILE_MD5,
    _COPY_DATA_TS
)
FROM (
    SELECT
        t.$1::TEXT,
        t.$2::TEXT,
        t.$3::TEXT,
        t.$4::TEXT,
        t.$5::TEXT,
        t.$6::TEXT,
        t.$7::TEXT,
        METADATA$FILENAME,
        METADATA$FILE_LAST_MODIFIED,
        METADATA$FILE_CONTENT_KEY,
        CURRENT_TIMESTAMP
    FROM @STAGE_SCH.CSV_STG/initial/location t
)
FILE_FORMAT = (
    FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT'
)
ON_ERROR = ABORT_STATEMENT;
