USE ROLE SYSADMIN;

-- creating warehouse
CREATE WAREHOUSE IF NOT EXISTS ADHOC_WH
    COMMENT = 'Warehouse for project queries'
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_RESUME = TRUE
    AUTO_SUSPEND = 60
    ENABLE_QUERY_ACCELERATION = FALSE
    WAREHOUSE_TYPE = 'STANDARD'
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    SCALING_POLICY = 'STANDARD'
    INITIALLY_SUSPENDED = TRUE;

--creating database
CREATE DATABASE IF NOT EXISTS SANDBOX;

USE DATABASE SANDBOX;

--creating schema
CREATE SCHEMA IF NOT EXISTS STAGE_SCH;
CREATE SCHEMA IF NOT EXISTS CLEAN_SCH;
CREATE SCHEMA IF NOT EXISTS CONSUMPTION_SCH;
CREATE SCHEMA IF NOT EXISTS COMMON;

USE SCHEMA STAGE_SCH;

CREATE FILE FORMAT IF NOT EXISTS STAGE_SCH.CSV_FILE_FORMAT
    TYPE = 'CSV'
    COMPRESSION = 'AUTO'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '\042'
    NULL_IF = ('\\N');

CREATE STAGE IF NOT EXIST STAGE_SCH.CSV_STG
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Internal stage for project files';

CREATE OR REPLACE TAG COMMON.PII_POLICY_TAG
    ALLOWED_VALUES 'PII', 'PRICE', 'SENSITIVE', 'EMAIL'
    COMMENT = 'Used to mark sensitive data';

CREATE OR REPLACE MASKING POLICY COMMON.PII_MASKING_POLICY
    AS (pii_text STRING)
    RETURNS STRING ->
    TO_VARCHAR('** PII **');

CREATE OR REPLACE MASKING POLICY COMMON.EMAIL_MASKING_POLICY
    AS (email_text STRING)
    RETURNS STRING ->
    TO_VARCHAR('** EMAIL **');

CREATE OR REPLACE MASKING POLICY COMMON.PHONE_MASKING_POLICY
    AS (phone STRING)
    RETURNS STRING ->
    TO_VARCHAR('** Phone **');

--checking
LIST @STAGE_SCH.CSV_STG/initial;
